/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoutienRouteImport } from './routes/soutien'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PourVousRouteImport } from './routes/pour-vous'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as AVenirRouteImport } from './routes/a-venir'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as AnimeSaisonRouteImport } from './routes/anime.saison'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedMesListesRouteImport } from './routes/_authenticated/mes-listes'
import { Route as MediaSourceIdRouteImport } from './routes/media.$source.$id'
import { Route as FranchiseSourceIdRouteImport } from './routes/franchise.$source.$id'

const SoutienRoute = SoutienRouteImport.update({
  id: '/soutien',
  path: '/soutien',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PourVousRoute = PourVousRouteImport.update({
  id: '/pour-vous',
  path: '/pour-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AVenirRoute = AVenirRouteImport.update({
  id: '/a-venir',
  path: '/a-venir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeSaisonRoute = AnimeSaisonRouteImport.update({
  id: '/saison',
  path: '/saison',
  getParentRoute: () => AnimeRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesListesRoute = AuthenticatedMesListesRouteImport.update({
  id: '/mes-listes',
  path: '/mes-listes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MediaSourceIdRoute = MediaSourceIdRouteImport.update({
  id: '/media/$source/$id',
  path: '/media/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseSourceIdRoute = FranchiseSourceIdRouteImport.update({
  id: '/franchise/$source/$id',
  path: '/franchise/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-venir': typeof AVenirRoute
  '/anime': typeof AnimeRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendrier': typeof CalendrierRoute
  '/films': typeof FilmsRoute
  '/pour-vous': typeof PourVousRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutien': typeof SoutienRoute
  '/mes-listes': typeof AuthenticatedMesListesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/anime/saison': typeof AnimeSaisonRoute
  '/anime/': typeof AnimeIndexRoute
  '/franchise/$source/$id': typeof FranchiseSourceIdRoute
  '/media/$source/$id': typeof MediaSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-venir': typeof AVenirRoute
  '/auth': typeof AuthRoute
  '/calendrier': typeof CalendrierRoute
  '/films': typeof FilmsRoute
  '/pour-vous': typeof PourVousRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutien': typeof SoutienRoute
  '/mes-listes': typeof AuthenticatedMesListesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/anime/saison': typeof AnimeSaisonRoute
  '/anime': typeof AnimeIndexRoute
  '/franchise/$source/$id': typeof FranchiseSourceIdRoute
  '/media/$source/$id': typeof MediaSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-venir': typeof AVenirRoute
  '/anime': typeof AnimeRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendrier': typeof CalendrierRoute
  '/films': typeof FilmsRoute
  '/pour-vous': typeof PourVousRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutien': typeof SoutienRoute
  '/_authenticated/mes-listes': typeof AuthenticatedMesListesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/anime/saison': typeof AnimeSaisonRoute
  '/anime/': typeof AnimeIndexRoute
  '/franchise/$source/$id': typeof FranchiseSourceIdRoute
  '/media/$source/$id': typeof MediaSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-venir'
    | '/anime'
    | '/auth'
    | '/calendrier'
    | '/films'
    | '/pour-vous'
    | '/recherche'
    | '/series'
    | '/sitemap.xml'
    | '/soutien'
    | '/mes-listes'
    | '/profil'
    | '/anime/saison'
    | '/anime/'
    | '/franchise/$source/$id'
    | '/media/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-venir'
    | '/auth'
    | '/calendrier'
    | '/films'
    | '/pour-vous'
    | '/recherche'
    | '/series'
    | '/sitemap.xml'
    | '/soutien'
    | '/mes-listes'
    | '/profil'
    | '/anime/saison'
    | '/anime'
    | '/franchise/$source/$id'
    | '/media/$source/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-venir'
    | '/anime'
    | '/auth'
    | '/calendrier'
    | '/films'
    | '/pour-vous'
    | '/recherche'
    | '/series'
    | '/sitemap.xml'
    | '/soutien'
    | '/_authenticated/mes-listes'
    | '/_authenticated/profil'
    | '/anime/saison'
    | '/anime/'
    | '/franchise/$source/$id'
    | '/media/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AVenirRoute: typeof AVenirRoute
  AnimeRoute: typeof AnimeRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendrierRoute: typeof CalendrierRoute
  FilmsRoute: typeof FilmsRoute
  PourVousRoute: typeof PourVousRoute
  RechercheRoute: typeof RechercheRoute
  SeriesRoute: typeof SeriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoutienRoute: typeof SoutienRoute
  FranchiseSourceIdRoute: typeof FranchiseSourceIdRoute
  MediaSourceIdRoute: typeof MediaSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soutien': {
      id: '/soutien'
      path: '/soutien'
      fullPath: '/soutien'
      preLoaderRoute: typeof SoutienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour-vous': {
      id: '/pour-vous'
      path: '/pour-vous'
      fullPath: '/pour-vous'
      preLoaderRoute: typeof PourVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-venir': {
      id: '/a-venir'
      path: '/a-venir'
      fullPath: '/a-venir'
      preLoaderRoute: typeof AVenirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/saison': {
      id: '/anime/saison'
      path: '/saison'
      fullPath: '/anime/saison'
      preLoaderRoute: typeof AnimeSaisonRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-listes': {
      id: '/_authenticated/mes-listes'
      path: '/mes-listes'
      fullPath: '/mes-listes'
      preLoaderRoute: typeof AuthenticatedMesListesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/media/$source/$id': {
      id: '/media/$source/$id'
      path: '/media/$source/$id'
      fullPath: '/media/$source/$id'
      preLoaderRoute: typeof MediaSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise/$source/$id': {
      id: '/franchise/$source/$id'
      path: '/franchise/$source/$id'
      fullPath: '/franchise/$source/$id'
      preLoaderRoute: typeof FranchiseSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMesListesRoute: typeof AuthenticatedMesListesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMesListesRoute: AuthenticatedMesListesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AnimeRouteChildren {
  AnimeSaisonRoute: typeof AnimeSaisonRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
}

const AnimeRouteChildren: AnimeRouteChildren = {
  AnimeSaisonRoute: AnimeSaisonRoute,
  AnimeIndexRoute: AnimeIndexRoute,
}

const AnimeRouteWithChildren = AnimeRoute._addFileChildren(AnimeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AVenirRoute: AVenirRoute,
  AnimeRoute: AnimeRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendrierRoute: CalendrierRoute,
  FilmsRoute: FilmsRoute,
  PourVousRoute: PourVousRoute,
  RechercheRoute: RechercheRoute,
  SeriesRoute: SeriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoutienRoute: SoutienRoute,
  FranchiseSourceIdRoute: FranchiseSourceIdRoute,
  MediaSourceIdRoute: MediaSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
