/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoutienRouteImport } from './routes/soutien'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PourVousRouteImport } from './routes/pour-vous'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ListesRouteImport } from './routes/listes'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as DesabonnementRouteImport } from './routes/desabonnement'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as AVenirRouteImport } from './routes/a-venir'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunauteIndexRouteImport } from './routes/communaute.index'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as MembreIdRouteImport } from './routes/membre.$id'
import { Route as CommunauteNouveauRouteImport } from './routes/communaute.nouveau'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AnimeSaisonRouteImport } from './routes/anime.saison'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedRecapRouteImport } from './routes/_authenticated/recap'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMesPlaylistsRouteImport } from './routes/_authenticated/mes-playlists'
import { Route as AuthenticatedMesListesRouteImport } from './routes/_authenticated/mes-listes'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedFondateurRouteImport } from './routes/_authenticated/fondateur'
import { Route as UniversSourceIdRouteImport } from './routes/univers.$source.$id'
import { Route as MediaSourceIdRouteImport } from './routes/media.$source.$id'
import { Route as FranchiseSourceIdRouteImport } from './routes/franchise.$source.$id'
import { Route as EntiteKindIdRouteImport } from './routes/entite.$kind.$id'
import { Route as CommunauteTIdRouteImport } from './routes/communaute.t.$id'
import { Route as CommunauteCSlugRouteImport } from './routes/communaute.c.$slug'
import { Route as AuthenticatedCommunauteDirectRouteImport } from './routes/_authenticated/communaute.direct'

const SoutienRoute = SoutienRouteImport.update({
  id: '/soutien',
  path: '/soutien',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PourVousRoute = PourVousRouteImport.update({
  id: '/pour-vous',
  path: '/pour-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ListesRoute = ListesRouteImport.update({
  id: '/listes',
  path: '/listes',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const DesabonnementRoute = DesabonnementRouteImport.update({
  id: '/desabonnement',
  path: '/desabonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AVenirRoute = AVenirRouteImport.update({
  id: '/a-venir',
  path: '/a-venir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteIndexRoute = CommunauteIndexRouteImport.update({
  id: '/communaute/',
  path: '/communaute/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimeRoute,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MembreIdRoute = MembreIdRouteImport.update({
  id: '/membre/$id',
  path: '/membre/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteNouveauRoute = CommunauteNouveauRouteImport.update({
  id: '/communaute/nouveau',
  path: '/communaute/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSaisonRoute = AnimeSaisonRouteImport.update({
  id: '/saison',
  path: '/saison',
  getParentRoute: () => AnimeRoute,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecapRoute = AuthenticatedRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesPlaylistsRoute =
  AuthenticatedMesPlaylistsRouteImport.update({
    id: '/mes-playlists',
    path: '/mes-playlists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesListesRoute = AuthenticatedMesListesRouteImport.update({
  id: '/mes-listes',
  path: '/mes-listes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFondateurRoute = AuthenticatedFondateurRouteImport.update({
  id: '/fondateur',
  path: '/fondateur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UniversSourceIdRoute = UniversSourceIdRouteImport.update({
  id: '/univers/$source/$id',
  path: '/univers/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSourceIdRoute = MediaSourceIdRouteImport.update({
  id: '/media/$source/$id',
  path: '/media/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseSourceIdRoute = FranchiseSourceIdRouteImport.update({
  id: '/franchise/$source/$id',
  path: '/franchise/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntiteKindIdRoute = EntiteKindIdRouteImport.update({
  id: '/entite/$kind/$id',
  path: '/entite/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteTIdRoute = CommunauteTIdRouteImport.update({
  id: '/communaute/t/$id',
  path: '/communaute/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteCSlugRoute = CommunauteCSlugRouteImport.update({
  id: '/communaute/c/$slug',
  path: '/communaute/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommunauteDirectRoute =
  AuthenticatedCommunauteDirectRouteImport.update({
    id: '/communaute/direct',
    path: '/communaute/direct',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-venir': typeof AVenirRoute
  '/anime': typeof AnimeRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendrier': typeof CalendrierRoute
  '/cgu': typeof CguRoute
  '/desabonnement': typeof DesabonnementRoute
  '/films': typeof FilmsRoute
  '/listes': typeof ListesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pour-vous': typeof PourVousRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutien': typeof SoutienRoute
  '/fondateur': typeof AuthenticatedFondateurRoute
  '/import': typeof AuthenticatedImportRoute
  '/mes-listes': typeof AuthenticatedMesListesRoute
  '/mes-playlists': typeof AuthenticatedMesPlaylistsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/recap': typeof AuthenticatedRecapRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/anime/saison': typeof AnimeSaisonRoute
  '/api/chat': typeof ApiChatRoute
  '/communaute/nouveau': typeof CommunauteNouveauRoute
  '/membre/$id': typeof MembreIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/anime/': typeof AnimeIndexRoute
  '/communaute/': typeof CommunauteIndexRoute
  '/communaute/direct': typeof AuthenticatedCommunauteDirectRoute
  '/communaute/c/$slug': typeof CommunauteCSlugRoute
  '/communaute/t/$id': typeof CommunauteTIdRoute
  '/entite/$kind/$id': typeof EntiteKindIdRoute
  '/franchise/$source/$id': typeof FranchiseSourceIdRoute
  '/media/$source/$id': typeof MediaSourceIdRoute
  '/univers/$source/$id': typeof UniversSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-venir': typeof AVenirRoute
  '/auth': typeof AuthRoute
  '/calendrier': typeof CalendrierRoute
  '/cgu': typeof CguRoute
  '/desabonnement': typeof DesabonnementRoute
  '/films': typeof FilmsRoute
  '/listes': typeof ListesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pour-vous': typeof PourVousRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutien': typeof SoutienRoute
  '/fondateur': typeof AuthenticatedFondateurRoute
  '/import': typeof AuthenticatedImportRoute
  '/mes-listes': typeof AuthenticatedMesListesRoute
  '/mes-playlists': typeof AuthenticatedMesPlaylistsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/recap': typeof AuthenticatedRecapRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/anime/saison': typeof AnimeSaisonRoute
  '/api/chat': typeof ApiChatRoute
  '/communaute/nouveau': typeof CommunauteNouveauRoute
  '/membre/$id': typeof MembreIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/actualites': typeof ActualitesIndexRoute
  '/anime': typeof AnimeIndexRoute
  '/communaute': typeof CommunauteIndexRoute
  '/communaute/direct': typeof AuthenticatedCommunauteDirectRoute
  '/communaute/c/$slug': typeof CommunauteCSlugRoute
  '/communaute/t/$id': typeof CommunauteTIdRoute
  '/entite/$kind/$id': typeof EntiteKindIdRoute
  '/franchise/$source/$id': typeof FranchiseSourceIdRoute
  '/media/$source/$id': typeof MediaSourceIdRoute
  '/univers/$source/$id': typeof UniversSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-venir': typeof AVenirRoute
  '/anime': typeof AnimeRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendrier': typeof CalendrierRoute
  '/cgu': typeof CguRoute
  '/desabonnement': typeof DesabonnementRoute
  '/films': typeof FilmsRoute
  '/listes': typeof ListesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pour-vous': typeof PourVousRoute
  '/recherche': typeof RechercheRoute
  '/series': typeof SeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutien': typeof SoutienRoute
  '/_authenticated/fondateur': typeof AuthenticatedFondateurRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/mes-listes': typeof AuthenticatedMesListesRoute
  '/_authenticated/mes-playlists': typeof AuthenticatedMesPlaylistsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/recap': typeof AuthenticatedRecapRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/anime/saison': typeof AnimeSaisonRoute
  '/api/chat': typeof ApiChatRoute
  '/communaute/nouveau': typeof CommunauteNouveauRoute
  '/membre/$id': typeof MembreIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/anime/': typeof AnimeIndexRoute
  '/communaute/': typeof CommunauteIndexRoute
  '/_authenticated/communaute/direct': typeof AuthenticatedCommunauteDirectRoute
  '/communaute/c/$slug': typeof CommunauteCSlugRoute
  '/communaute/t/$id': typeof CommunauteTIdRoute
  '/entite/$kind/$id': typeof EntiteKindIdRoute
  '/franchise/$source/$id': typeof FranchiseSourceIdRoute
  '/media/$source/$id': typeof MediaSourceIdRoute
  '/univers/$source/$id': typeof UniversSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-venir'
    | '/anime'
    | '/auth'
    | '/calendrier'
    | '/cgu'
    | '/desabonnement'
    | '/films'
    | '/listes'
    | '/mentions-legales'
    | '/pour-vous'
    | '/recherche'
    | '/series'
    | '/sitemap.xml'
    | '/soutien'
    | '/fondateur'
    | '/import'
    | '/mes-listes'
    | '/mes-playlists'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/profil'
    | '/recap'
    | '/statistiques'
    | '/actualites/$slug'
    | '/anime/saison'
    | '/api/chat'
    | '/communaute/nouveau'
    | '/membre/$id'
    | '/playlist/$id'
    | '/actualites/'
    | '/anime/'
    | '/communaute/'
    | '/communaute/direct'
    | '/communaute/c/$slug'
    | '/communaute/t/$id'
    | '/entite/$kind/$id'
    | '/franchise/$source/$id'
    | '/media/$source/$id'
    | '/univers/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-venir'
    | '/auth'
    | '/calendrier'
    | '/cgu'
    | '/desabonnement'
    | '/films'
    | '/listes'
    | '/mentions-legales'
    | '/pour-vous'
    | '/recherche'
    | '/series'
    | '/sitemap.xml'
    | '/soutien'
    | '/fondateur'
    | '/import'
    | '/mes-listes'
    | '/mes-playlists'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/profil'
    | '/recap'
    | '/statistiques'
    | '/actualites/$slug'
    | '/anime/saison'
    | '/api/chat'
    | '/communaute/nouveau'
    | '/membre/$id'
    | '/playlist/$id'
    | '/actualites'
    | '/anime'
    | '/communaute'
    | '/communaute/direct'
    | '/communaute/c/$slug'
    | '/communaute/t/$id'
    | '/entite/$kind/$id'
    | '/franchise/$source/$id'
    | '/media/$source/$id'
    | '/univers/$source/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-venir'
    | '/anime'
    | '/auth'
    | '/calendrier'
    | '/cgu'
    | '/desabonnement'
    | '/films'
    | '/listes'
    | '/mentions-legales'
    | '/pour-vous'
    | '/recherche'
    | '/series'
    | '/sitemap.xml'
    | '/soutien'
    | '/_authenticated/fondateur'
    | '/_authenticated/import'
    | '/_authenticated/mes-listes'
    | '/_authenticated/mes-playlists'
    | '/_authenticated/messages'
    | '/_authenticated/moderation'
    | '/_authenticated/notifications'
    | '/_authenticated/profil'
    | '/_authenticated/recap'
    | '/_authenticated/statistiques'
    | '/actualites/$slug'
    | '/anime/saison'
    | '/api/chat'
    | '/communaute/nouveau'
    | '/membre/$id'
    | '/playlist/$id'
    | '/actualites/'
    | '/anime/'
    | '/communaute/'
    | '/_authenticated/communaute/direct'
    | '/communaute/c/$slug'
    | '/communaute/t/$id'
    | '/entite/$kind/$id'
    | '/franchise/$source/$id'
    | '/media/$source/$id'
    | '/univers/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AVenirRoute: typeof AVenirRoute
  AnimeRoute: typeof AnimeRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendrierRoute: typeof CalendrierRoute
  CguRoute: typeof CguRoute
  DesabonnementRoute: typeof DesabonnementRoute
  FilmsRoute: typeof FilmsRoute
  ListesRoute: typeof ListesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PourVousRoute: typeof PourVousRoute
  RechercheRoute: typeof RechercheRoute
  SeriesRoute: typeof SeriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoutienRoute: typeof SoutienRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  ApiChatRoute: typeof ApiChatRoute
  CommunauteNouveauRoute: typeof CommunauteNouveauRoute
  MembreIdRoute: typeof MembreIdRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  CommunauteIndexRoute: typeof CommunauteIndexRoute
  CommunauteCSlugRoute: typeof CommunauteCSlugRoute
  CommunauteTIdRoute: typeof CommunauteTIdRoute
  EntiteKindIdRoute: typeof EntiteKindIdRoute
  FranchiseSourceIdRoute: typeof FranchiseSourceIdRoute
  MediaSourceIdRoute: typeof MediaSourceIdRoute
  UniversSourceIdRoute: typeof UniversSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soutien': {
      id: '/soutien'
      path: '/soutien'
      fullPath: '/soutien'
      preLoaderRoute: typeof SoutienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour-vous': {
      id: '/pour-vous'
      path: '/pour-vous'
      fullPath: '/pour-vous'
      preLoaderRoute: typeof PourVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listes': {
      id: '/listes'
      path: '/listes'
      fullPath: '/listes'
      preLoaderRoute: typeof ListesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desabonnement': {
      id: '/desabonnement'
      path: '/desabonnement'
      fullPath: '/desabonnement'
      preLoaderRoute: typeof DesabonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-venir': {
      id: '/a-venir'
      path: '/a-venir'
      fullPath: '/a-venir'
      preLoaderRoute: typeof AVenirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute/': {
      id: '/communaute/'
      path: '/communaute'
      fullPath: '/communaute/'
      preLoaderRoute: typeof CommunauteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membre/$id': {
      id: '/membre/$id'
      path: '/membre/$id'
      fullPath: '/membre/$id'
      preLoaderRoute: typeof MembreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute/nouveau': {
      id: '/communaute/nouveau'
      path: '/communaute/nouveau'
      fullPath: '/communaute/nouveau'
      preLoaderRoute: typeof CommunauteNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/saison': {
      id: '/anime/saison'
      path: '/saison'
      fullPath: '/anime/saison'
      preLoaderRoute: typeof AnimeSaisonRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recap': {
      id: '/_authenticated/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof AuthenticatedRecapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-playlists': {
      id: '/_authenticated/mes-playlists'
      path: '/mes-playlists'
      fullPath: '/mes-playlists'
      preLoaderRoute: typeof AuthenticatedMesPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-listes': {
      id: '/_authenticated/mes-listes'
      path: '/mes-listes'
      fullPath: '/mes-listes'
      preLoaderRoute: typeof AuthenticatedMesListesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fondateur': {
      id: '/_authenticated/fondateur'
      path: '/fondateur'
      fullPath: '/fondateur'
      preLoaderRoute: typeof AuthenticatedFondateurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/univers/$source/$id': {
      id: '/univers/$source/$id'
      path: '/univers/$source/$id'
      fullPath: '/univers/$source/$id'
      preLoaderRoute: typeof UniversSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$source/$id': {
      id: '/media/$source/$id'
      path: '/media/$source/$id'
      fullPath: '/media/$source/$id'
      preLoaderRoute: typeof MediaSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise/$source/$id': {
      id: '/franchise/$source/$id'
      path: '/franchise/$source/$id'
      fullPath: '/franchise/$source/$id'
      preLoaderRoute: typeof FranchiseSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entite/$kind/$id': {
      id: '/entite/$kind/$id'
      path: '/entite/$kind/$id'
      fullPath: '/entite/$kind/$id'
      preLoaderRoute: typeof EntiteKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute/t/$id': {
      id: '/communaute/t/$id'
      path: '/communaute/t/$id'
      fullPath: '/communaute/t/$id'
      preLoaderRoute: typeof CommunauteTIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute/c/$slug': {
      id: '/communaute/c/$slug'
      path: '/communaute/c/$slug'
      fullPath: '/communaute/c/$slug'
      preLoaderRoute: typeof CommunauteCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/communaute/direct': {
      id: '/_authenticated/communaute/direct'
      path: '/communaute/direct'
      fullPath: '/communaute/direct'
      preLoaderRoute: typeof AuthenticatedCommunauteDirectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFondateurRoute: typeof AuthenticatedFondateurRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMesListesRoute: typeof AuthenticatedMesListesRoute
  AuthenticatedMesPlaylistsRoute: typeof AuthenticatedMesPlaylistsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRecapRoute: typeof AuthenticatedRecapRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedCommunauteDirectRoute: typeof AuthenticatedCommunauteDirectRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFondateurRoute: AuthenticatedFondateurRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMesListesRoute: AuthenticatedMesListesRoute,
  AuthenticatedMesPlaylistsRoute: AuthenticatedMesPlaylistsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRecapRoute: AuthenticatedRecapRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedCommunauteDirectRoute: AuthenticatedCommunauteDirectRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AnimeRouteChildren {
  AnimeSaisonRoute: typeof AnimeSaisonRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
}

const AnimeRouteChildren: AnimeRouteChildren = {
  AnimeSaisonRoute: AnimeSaisonRoute,
  AnimeIndexRoute: AnimeIndexRoute,
}

const AnimeRouteWithChildren = AnimeRoute._addFileChildren(AnimeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AVenirRoute: AVenirRoute,
  AnimeRoute: AnimeRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendrierRoute: CalendrierRoute,
  CguRoute: CguRoute,
  DesabonnementRoute: DesabonnementRoute,
  FilmsRoute: FilmsRoute,
  ListesRoute: ListesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PourVousRoute: PourVousRoute,
  RechercheRoute: RechercheRoute,
  SeriesRoute: SeriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoutienRoute: SoutienRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  ApiChatRoute: ApiChatRoute,
  CommunauteNouveauRoute: CommunauteNouveauRoute,
  MembreIdRoute: MembreIdRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  CommunauteIndexRoute: CommunauteIndexRoute,
  CommunauteCSlugRoute: CommunauteCSlugRoute,
  CommunauteTIdRoute: CommunauteTIdRoute,
  EntiteKindIdRoute: EntiteKindIdRoute,
  FranchiseSourceIdRoute: FranchiseSourceIdRoute,
  MediaSourceIdRoute: MediaSourceIdRoute,
  UniversSourceIdRoute: UniversSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
